"""Attachment

Revision ID: 7168dcf24b13
Revises: bc5e07390c03
Create Date: 2024-07-02 14:09:11.387174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages

# revision identifiers, used by Alembic.
revision: str = '7168dcf24b13'
down_revision: Union[str, None] = 'bc5e07390c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('file', fastapi_storages.integrations.sqlalchemy.FileType(storage=fastapi_storages.FileSystemStorage(path="_uploads")), nullable=True),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment')
    # ### end Alembic commands ###
